import ts from 'typescript';
export declare const GENERATED_FILE_HEADER = "// <auto-generated>\n// This code was auto-generated.\n// Changes to this file may cause incorrect behavior and will be lost if\n// the code is regenerated.\n// </auto-generated>";
export declare function generateFile(program: ts.Program, sourceFile: ts.SourceFile, fileName: string): void;
export declare function generateClass(program: ts.Program, classDeclaration: ts.ClassDeclaration, generate: (program: ts.Program, classDeclaration: ts.ClassDeclaration) => ts.SourceFile): void;
export default function createEmitter(jsDocMarker: string, generate: (program: ts.Program, classDeclaration: ts.ClassDeclaration) => ts.SourceFile): (program: ts.Program, _diagnostics: ts.Diagnostic[]) => void;
