import "./alphaTab.polyfills";
export { CoreSettings, FontFileFormat } from "./CoreSettings";
export { DisplaySettings, SystemsLayoutMode } from "./DisplaySettings";
export { LayoutMode } from "./LayoutMode";
export { StaveProfile } from "./StaveProfile";
export { ImporterSettings } from "./ImporterSettings";
export { ExporterSettings } from "./ExporterSettings";
export { FingeringMode, NotationMode, NotationSettings, TabRhythmMode, NotationElement } from "./NotationSettings";
export { PlayerSettings, ScrollMode, SlidePlaybackSettings, VibratoPlaybackSettings, PlayerOutputMode, PlayerMode } from "./PlayerSettings";
export { ProgressEventArgs } from "./ProgressEventArgs";
export { RenderingResources } from "./RenderingResources";
export type { SmuflEngravingDefaults, SmuflGlyphBoundingBox, SmuflGlyphWithAnchor, SmuflMetadata, } from "./SmuflMetadata";
export { EngravingSettings, EngravingStemInfo } from "./EngravingSettings";
export { ResizeEventArgs } from "./ResizeEventArgs";
export { Settings } from "./Settings";
export { AlphaTabError, AlphaTabErrorType } from "./AlphaTabError";
export { FormatError } from "./FormatError";
export { LogLevel } from "./LogLevel";
export { Logger, ConsoleLogger } from "./Logger";
export type { ILogger } from "./Logger";
export { FileLoadError } from "./FileLoadError";
export { Environment, RenderEngineFactory } from "./Environment";
export type { IEventEmitter, IEventEmitterOfT } from "./EventEmitter";
export { AlphaTabApi } from "./platform/javascript/AlphaTabApi";
export { AlphaTabApiBase, type PlaybackHighlightChangeEventArgs } from "./AlphaTabApiBase";
export type { IScrollHandler } from "./ScrollHandlers";
export { WebPlatform } from "./platform/javascript/WebPlatform";
export { VersionInfo as meta } from "./generated/VersionInfo";
export * as importer from "./importer/_barrel";
export * as io from "./io/_barrel";
export * as exporter from "./exporter/_barrel";
export * as midi from "./midi/_barrel";
export * as model from "./model/_barrel";
export * as rendering from "./rendering/_barrel";
export * as platform from "./platform/_barrel";
export * as synth from "./synth/_barrel";
export * as json from "./generated/_jsonbarrel";
