import { type IEventEmitter, type IEventEmitterOfT } from "./../../EventEmitter";
import type { LogLevel } from "./../../LogLevel";
import type { MidiEventType } from "./../../midi/MidiEvent";
import type { MidiFile } from "./../../midi/MidiFile";
import type { Score } from "./../../model/Score";
import type { IAlphaSynthWorker, IAlphaSynthWorkerMessage } from "./AlphaTabWorkerProtocol";
import type { Settings } from "./../../Settings";
import type { BackingTrackSyncPoint, IAlphaSynth } from "./../../synth/IAlphaSynth";
import type { ISynthOutput } from "./../../synth/ISynthOutput";
import { MidiEventsPlayedEventArgs } from "./../../synth/MidiEventsPlayedEventArgs";
import type { PlaybackRange } from "./../../synth/PlaybackRange";
import { PlaybackRangeChangedEventArgs } from "./../../synth/PlaybackRangeChangedEventArgs";
import { PlayerState } from "./../../synth/PlayerState";
import { PlayerStateChangedEventArgs } from "./../../synth/PlayerStateChangedEventArgs";
import { PositionChangedEventArgs } from "./../../synth/PositionChangedEventArgs";
/**
 * a WebWorker based alphaSynth which uses the given player as output.
 * @internal
 */
export declare class AlphaSynthWebWorkerApi implements IAlphaSynth {
    private _synth;
    private _output;
    private _workerIsReadyForPlayback;
    private _workerIsReady;
    private _outputIsReady;
    private _state;
    private _masterVolume;
    private _metronomeVolume;
    private _countInVolume;
    private _playbackSpeed;
    private _isLooping;
    private _playbackRange;
    private _midiEventsPlayedFilter;
    private _loadedMidiInfo?;
    private _currentPosition;
    get output(): ISynthOutput;
    get isReady(): boolean;
    get isReadyForPlayback(): boolean;
    get state(): PlayerState;
    get logLevel(): LogLevel;
    get worker(): IAlphaSynthWorker;
    set logLevel(value: LogLevel);
    get masterVolume(): number;
    set masterVolume(value: number);
    get metronomeVolume(): number;
    set metronomeVolume(value: number);
    get countInVolume(): number;
    set countInVolume(value: number);
    get midiEventsPlayedFilter(): MidiEventType[];
    set midiEventsPlayedFilter(value: MidiEventType[]);
    get playbackSpeed(): number;
    set playbackSpeed(value: number);
    get loadedMidiInfo(): PositionChangedEventArgs | undefined;
    get currentPosition(): PositionChangedEventArgs;
    get tickPosition(): number;
    set tickPosition(value: number);
    get timePosition(): number;
    set timePosition(value: number);
    get isLooping(): boolean;
    set isLooping(value: boolean);
    get playbackRange(): PlaybackRange | null;
    set playbackRange(value: PlaybackRange | null);
    constructor(player: ISynthOutput, settings: Settings, synthWorker: IAlphaSynthWorker);
    destroy(): void;
    play(): boolean;
    pause(): void;
    playPause(): void;
    stop(): void;
    playOneTimeMidiFile(midi: MidiFile): void;
    loadSoundFont(data: Uint8Array, append: boolean): void;
    resetSoundFonts(): void;
    loadMidiFile(midi: MidiFile): void;
    applyTranspositionPitches(transpositionPitches: Map<number, number>): void;
    setChannelTranspositionPitch(channel: number, semitones: number): void;
    setChannelMute(channel: number, mute: boolean): void;
    resetChannelStates(): void;
    setChannelSolo(channel: number, solo: boolean): void;
    setChannelVolume(channel: number, volume: number): void;
    handleWorkerMessage(e: MessageEvent<IAlphaSynthWorkerMessage>): void;
    private _checkReady;
    private _checkReadyForPlayback;
    readonly ready: IEventEmitter;
    readonly readyForPlayback: IEventEmitter;
    readonly finished: IEventEmitter;
    readonly soundFontLoaded: IEventEmitter;
    readonly soundFontLoadFailed: IEventEmitterOfT<Error>;
    readonly midiLoaded: IEventEmitterOfT<PositionChangedEventArgs>;
    readonly midiLoadFailed: IEventEmitterOfT<Error>;
    readonly stateChanged: IEventEmitterOfT<PlayerStateChangedEventArgs>;
    readonly positionChanged: IEventEmitterOfT<PositionChangedEventArgs>;
    readonly midiEventsPlayed: IEventEmitterOfT<MidiEventsPlayedEventArgs>;
    readonly playbackRangeChanged: IEventEmitterOfT<PlaybackRangeChangedEventArgs>;
    onOutputSampleRequest(): void;
    onOutputSamplesPlayed(samples: number): void;
    private _onOutputReady;
    loadBackingTrack(_score: Score): void;
    updateSyncPoints(_syncPoints: BackingTrackSyncPoint[]): void;
}
